### ISSUE TITLE
Fix 1.16.40 and 1.16.50

### ISSUE THREAD

**Issue by bundabrg** [bundabrg/Reversion#11]
There appears to be an issue with ResourcePackStackPacket.

Sending:
```
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 00 00 00 07 31 2e 31 36 2e 34 30 00 00 00 00 00 |....1.16.40.....|
+--------+-------------------------------------------------+----------------+

```

```
com.nukkitx.protocol.bedrock.exception.PacketSerializeException: Error whilst deserializing ResourcePackStackPacket(forcedToAccept=false, behaviorPacks=[], resourcePacks=[], gameVersion=null, experiments=[ExperimentData(name=legacy_experiment, enabled=true)], experimentsPreviouslyToggled=false)
        at com.nukkitx.protocol.bedrock.BedrockPacketCodec.tryDecode(BedrockPacketCodec.java:61) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at com.nukkitx.protocol.bedrock.wrapper.BedrockWrapperSerializerV9_10.deserialize(BedrockWrapperSerializerV9_10.java:74) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at com.nukkitx.protocol.bedrock.BedrockSession.onWrappedPacket(BedrockSession.java:285) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener.onEncapsulated(BedrockRakNetSessionListener.java:32) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at com.nukkitx.network.raknet.RakNetSession.onEncapsulatedInternal(RakNetSession.java:300) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at com.nukkitx.network.raknet.RakNetSession.onOrderedReceived(RakNetSession.java:427) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at com.nukkitx.network.raknet.RakNetSession.checkForOrdered(RakNetSession.java:405) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at com.nukkitx.network.raknet.RakNetSession.onRakNetDatagram(RakNetSession.java:398) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at com.nukkitx.network.raknet.RakNetSession.onDatagram(RakNetSession.java:272) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at com.nukkitx.network.raknet.RakNetClient$ClientDatagramHandler.channelRead(RakNetClient.java:177) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at io.netty.channel.epoll.EpollDatagramChannel.read(EpollDatagramChannel.java:688) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at io.netty.channel.epoll.EpollDatagramChannel.access$100(EpollDatagramChannel.java:57) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at io.netty.channel.epoll.EpollDatagramChannel$EpollDatagramChannelUnsafe.epollInReady(EpollDatagramChannel.java:507) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$1.run(AbstractEpollChannel.java:394) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at java.lang.Thread.run(Thread.java:834) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Tried to read 49 bytes but only has 11 readable
        at com.nukkitx.network.util.Preconditions.checkArgument(Preconditions.java:292) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at com.nukkitx.protocol.bedrock.BedrockPacketHelper.readByteArray(BedrockPacketHelper.java:242) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at com.nukkitx.protocol.bedrock.BedrockPacketHelper.readString(BedrockPacketHelper.java:269) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at com.nukkitx.protocol.bedrock.v388.serializer.ResourcePackStackSerializer_v388.deserialize(ResourcePackStackSerializer_v388.java:29) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at com.nukkitx.protocol.bedrock.v388.serializer.ResourcePackStackSerializer_v388.deserialize(ResourcePackStackSerializer_v388.java:11) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at com.nukkitx.protocol.bedrock.BedrockPacketSerializer.deserialize(BedrockPacketSerializer.java:21) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at com.nukkitx.protocol.bedrock.BedrockPacketCodec.tryDecode(BedrockPacketCodec.java:59) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        ... 26 more
```

**Comment by CCF100** [comment]
![image](https://user-images.githubusercontent.com/29297989/100120682-d963a100-2e3d-11eb-9f77-24651ab2aedc.png)
